Repository fortran-lang/fortran-lang.org, pull requests merged in 2021-06, with the labels that each got.

#263 Monthly newsletter: June
  _posts/2021-06-01-Fortran-Newsletter-June-2021.md
  community/github_stats_data/data-fortran-lang-fortran-lang.org.json
  community/github_stats_data/data-fortran-lang-fpm.json
  community/github_stats_data/data-fortran-lang-stdlib.json
  community/github_stats_data/data-j3-fortran-fortran_proposals.json
Labels: news

#273 add the SNaC package ?
  _data/package_index.yml
Labels: packages

#272 Add QUICK to packages
  _data/package_index.yml
Labels: packages

#275 Add crest program to package index
  _data/package_index.yml
Labels: packages

#255 Quickstart edits
  CONTRIBUTING.md
  assets/css/main.css
  learn/quickstart/arrays_strings.md
  learn/quickstart/derived_types.md
  learn/quickstart/hello_world.md
  learn/quickstart/operators_control_flow.md
  learn/quickstart/organising_code.md
  learn/quickstart/variables.md
Labels: learn

#276 Add LATTE tight-binding molecular dynamics code to package index
  _data/package_index.yml
Labels: packages
